version: "4.0"
services:
    zabbix-proxy-v4:
        image: azcorptechbr/azmon-proxy5:latest
        container_name: azmon-proxy5
        hostname: azmon-proxy5
        ports:
            - $IP:$ZBX_SERVER_PORT:$ZBX_SERVER_PORT
        cap_add: ['NET_ADMIN']
        devices:
            - /dev/net/tun
        environment:
            - ZBX_HOSTNAME=$ZBX_HOSTNAME
            - ZBX_SERVER_HOST=$ZBX_SERVER_HOST
            - ZBX_DEBUGLEVEL=$ZBX_DEBUGLEVEL
            - ZBX_TIMEOUT=$ZBX_TIMEOUT
            - ZBX_PROXYLOCALBUFFER=$ZBX_PROXYLOCALBUFFER
            - ZBX_PROXYOFFLINEBUFFER=$ZBX_PROXYOFFLINEBUFFER
            - ZBX_CONFIGFREQUENCY=$ZBX_CONFIGFREQUENCY
            - ZBX_STARTPOLLERS=$ZBX_STARTPOLLERS
            - ZBX_STARTPOLLERSUNREACHABLE=$ZBX_STARTPOLLERSUNREACHABLE
            - ZBX_STARTTRAPPERS=$ZBX_STARTTRAPPERS
            - ZBX_STARTPINGERS=$ZBX_STARTPINGERS
            - ZBX_CACHESIZE=$ZBX_CACHESIZE
            - ZBX_HISTORYCACHESIZE=$ZBX_HISTORYCACHESIZE
            - ZBX_HISTORYINDEXCACHESIZE=$ZBX_HISTORYINDEXCACHESIZE
            - ZBX_STARTVMWARECOLLECTORS=$ZBX_STARTVMWARECOLLECTORS
            - ZBX_VMWAREFREQUENCY=$ZBX_VMWAREFREQUENCY
            - ZBX_VMWAREPERFFREQUENCY=$ZBX_VMWAREPERFFREQUENCY
            - ZBX_VMWARECACHESIZE=$ZBX_VMWARECACHESIZE
            - ZBX_VMWARETIMEOUT=$ZBX_VMWARETIMEOUT
            - TNS_ADMIN=/usr/lib/oracle/12.1/client64/network/admin
            - ZBX_TLSCONNECT=psk
            - ZBX_TLSPSKIDENTITY=$ZBX_HOSTNAME
            - ZBX_TLSPSKFILE=tls.psk
            - ZBX_SERVER_PORT=$ZBX_SERVER_PORT
            - ZBX_ENABLEREMOTECOMMANDS=1
        volumes:
            - /opt/azcorp/zabbix-proxy/scripts/externalscripts:/usr/lib/zabbix/externalscripts
            - /opt/azcorp/zabbix-proxy/scripts/alertscripts:/usr/lib/zabbix/alertscripts
            - /opt/azcorp/zabbix-proxy/tnsnames.ora:/usr/lib/oracle/12.1/client64/network/admin/tnsnames.ora
            - /opt/azcorp/zabbix-proxy/tls.psk:/var/lib/zabbix/enc/tls.psk
            - /usr/share/snmp/mibs:/usr/share/snmp/mibs
            - /etc/odbc.ini:/etc/odbc.ini
            - /etc/localtime:/etc/localtime:ro
            - /etc/hosts:/etc/hosts
#            - /etc/resolv.conf:/etc/resolv.conf
        restart: always
        networks:
           zbx-network:
              ipv4_address: $IP_CONTAINER
networks:
  zbx-network:
    ipam:
      driver: default
      config:
        - subnet: $IP_SUBNET
